name: Streamlit Deployment

on:
  push:
    branches:
      - main  # or the branch you're using

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Streamlit works well with Python 3.8+

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit
      run: streamlit run app.py
